leftnav:
- identifier: 4d2b970f-2491-d979-007d-d30ba5fd64f1
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 583a2973-6531-c559-cb4e-90daa6e66a6d
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 31f7ea58-a825-ab20-2bc3-07b48f510ff7
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 87133651-b560-5435-2997-d382002857f2
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: fe092b65-2ae1-d4bb-c399-c60b523b10f7
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
